project:
  type: website

website:
  description: "Personal blog for Andrew Boney"
  site-url: https://andrewboney.github.io/andrew_boney_blog/
  title: "Andrew Boney Blog"
  navbar:
    right:
      - text: Blog
        href: index.qmd
      - text: Portfolio
        href: portfolio.qmd
      - about.qmd
      - icon: github
        href: https://github.com/andrewboney
      - icon: twitter
        href: https://twitter.com/barry_bones_
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



